version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11.2
    environment:
    - POSTGRES_PASSWORD=pg
    - POSTGRES_USER=postgres
    - POSTGRES_DB=pg
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    restart: always
  web:
    restart: always
    working_dir: /sring-security-auth-server
    build:
      context: ./sring-security-auth-server
      dockerfile: Dockerfile
    ports:
    - 8081:8081
    command: 'mvn clean spring-boot:run'
    depends_on:
    - db